src/main/java/com/codestates/coco/contents/service/ContentService.java
* add contents-service-getContents ResponseStatusException
* add contents-service-deleteContents ResponseStatusException
* add contents-service-putContents ResponseStatusException
=> fix: add contents-service Exception

src/main/java/com/codestates/coco/CocoApplication.java, src/main/java/com/codestates/coco/comment/controller/CommentController.java, src/main/java/com/codestates/coco/comment/domain/Comment.java, src/main/java/com/codestates/coco/comment/domain/CommentDTO.java, src/main/java/com/codestates/coco/comment/repository/CommentRepository.java, src/main/java/com/codestates/coco/comment/service/CommentService.java, src/main/java/com/codestates/coco/contents/domain/Content.java, src/main/java/com/codestates/coco/contents/domain/ContentDTO.java, src/main/java/com/codestates/coco/contents/domain/ContentGetDTO.java, src/main/java/com/codestates/coco/contents/service/ContentService.java, src/main/java/com/codestates/coco/user/domain/User.java
* Contents Update 및 Delete 기능 추가
* Comment Create, Read, Update 및 Delete 기능 추가
=> Contents, Comment 기능 추가

frontend/src/pages/Login.tsx, frontend/src/pages/StudyBoardDetail.tsx
1. 로그인 페이지 자체 유효성 검사 추가 
2. 디테일페이지 API 연결 
3. 댓글창에 패딩 추가
=> Feat: 자체 유효성 검사 추가 , 디테일 페이지 Api 연결 , Padding 추가 

frontend/src/apis/apiClient.ts, frontend/src/pages/Signup.tsx, frontend/src/pages/StudyBoardWrite.tsx
- 회원가입 페이지 유효성 검사 방식 변경
- 회원가입 페이지, 글쓰기 페이지 서버 연동(axios)
- 회원가입 페이지 비밀번호 확인 기능 추가, username 유효성 검사 기준 추가
resolved: #56
=> Feat: "회원가입 페이지, 글쓰기 페이지 서버 연동 및 유효성 검사 방식 변경" 

src/main/java/com/codestates/coco/contents/controller/ContentController.java, src/main/java/com/codestates/coco/contents/domain/ContentTitleDTO.java, src/main/java/com/codestates/coco/contents/repository/ContentRepository.java, src/main/java/com/codestates/coco/contents/service/ContentService.java
* add file contents-domain-ContentTitleDTO
* add contents-controller [Get]/page/{page:int}
* add contents-service pagelogic
* add contents-repository query (sort, pagealbe)
* fix contents-service createPostLogic +now Date
=> feat: contents pagination 

src/main/java/com/codestates/coco/contents/controller/ContentController.java, src/main/java/com/codestates/coco/contents/repository/ContentRepository.java, src/main/java/com/codestates/coco/contents/service/ContentService.java
* add ResponseEntity for http status code
* change gettitlecontent- return type
Resolves: #14
=> feat: content-controller

frontend/src/components/BoardContentBox/BoardContentBox.tsx, frontend/src/lib/types/index.ts, frontend/src/pages/StudyBoard/StudyBoard.tsx, frontend/src/pages/StudyBoardDetail/components/Body.tsx, frontend/src/pages/StudyBoardDetail/components/Header.tsx, frontend/src/pages/StudyBoardDetail/index.tsx
=> FE: 무한스크롤 기능 추가, 상세 페이지 진입

frontend/package-lock.json, frontend/package.json, frontend/src/pages/BoardWrite.tsx
- react-intersection-observer 설치
- 글쓰기 페이지 api 업데이트에 따른 코드 수정
=> FE: package.json 업데이트 및 글쓰기 페이지 api 수정

frontend/src/pages/Signup/style.ts
- props 적용에 따른 ErrorText style 코드 수정
=> FE: ErrorText style 수정

build.gradle, src/main/java/com/codestates/coco/aop/LogAop.java, src/main/java/com/codestates/coco/aop/LogExecutionTime.java, src/main/java/com/codestates/coco/comment/controller/CommentController.java, src/main/java/com/codestates/coco/comment/domain/CommentDTO.java, src/main/java/com/codestates/coco/comment/domain/CommentUserDTO.java, src/main/java/com/codestates/coco/comment/repository/CommentRepository.java, src/main/java/com/codestates/coco/comment/service/CommentService.java, src/main/java/com/codestates/coco/common/ErrorCode.java, src/main/java/com/codestates/coco/contents/controller/ContentController.java, src/main/java/com/codestates/coco/contents/service/ContentService.java, src/main/java/com/codestates/coco/user/config/CorsConfig.java, src/main/java/com/codestates/coco/user/controller/UserController.java, src/main/java/com/codestates/coco/user/domain/User.java, src/main/java/com/codestates/coco/user/domain/UserDTO.java, src/main/java/com/codestates/coco/user/jwt/JwtAuthenticationFilter.java, src/main/java/com/codestates/coco/user/service/UserService.java
* author와 username 비교 권한 필터링
* 사용자가 작성한 Comment에 대한 Content 조회
* Logging 추가
Resolves: #94, #97
Related to: #96
=> BE: #94 #96 #97

frontend/src/components/ContentLayout/Right/RightMenubar.tsx, frontend/src/components/ContentLayout/Right/style.ts, frontend/src/components/Login/LoginForm.tsx, frontend/src/components/NaviHeader/NaviHeader.tsx, frontend/src/pages/UserProfile/UserProfile.tsx
* userProfile API 연결
* rightSideBar API 연결
=> FE : "UserProfileAPI 연결 RightSideBar API 연결"

frontend/src/components/ContentLayout/Right/RightMenubar.tsx, frontend/src/components/Login/LoginForm.tsx, frontend/src/pages/Main/index.tsx, frontend/src/pages/UserProfile/UserProfile.tsx
* FE : "로그인 유저 정보 조회 추가 , 유저 네임 중복 체크 로직 연결"
=> FE : "로그인 유저 정보 조회 추가 , 유저 네임 중복 체크 로직 연결"

frontend/src/pages/BoardEdit/BoardEdit.tsx, frontend/src/pages/Signup/Signup.tsx
- 글 수정 페이지 데이터 불러오지 못하는 오류 해결
- 글 수정 페이지 api 모듈 분리
- Signup 페이지 api 모듈 분리
=> FE: 글 수정페이지 오류 수정 및 api 모듈 분리

frontend/src/apis/apiClient.ts, frontend/src/apis/types.ts
- api 모듈 분리에 따른 일부 api 수정
- BoardForm interface 수정
=> FE: api 및 type 정의 수정

frontend/src/components/Comment/Comment.tsx, frontend/src/pages/StudyBoard/StudyBoard.tsx, frontend/src/pages/StudyBoard/style.ts, frontend/src/pages/StudyBoardDetail/StudyBoardDetail.tsx, frontend/src/pages/StudyBoardDetail/components/Body.tsx, frontend/src/pages/StudyBoardDetail/components/Header.tsx, frontend/src/pages/StudyBoardDetail/style.ts
=> FE: favor기능제외 게시판 기능 안정화

frontend/src/Router.tsx, frontend/src/pages/BoardEdit/BoardEdit.tsx, frontend/src/pages/BoardEdit/style.ts, frontend/src/pages/BoardWrite/style.ts
- 404페이지 라우터 연결
- 게시글 수정 접근 제한 기능 추가
- 글작성 및 글 수정 페이지 제목 및 태그 input CSS 수정
=> FE: 404페이지 라우터 연결, 게시글 수정 접근 제한 기능 추가, 글작성 및 글 수정 페이지 CSS 수정

frontend/src/Router.tsx, frontend/src/components/Comment/Comment.tsx, frontend/src/pages/BoardEdit/BoardEdit.tsx, frontend/src/pages/BoardEdit/style.ts, frontend/src/pages/BoardWrite/style.ts, frontend/src/pages/StudyBoard/StudyBoard.tsx, frontend/src/pages/StudyBoard/style.ts, frontend/src/pages/StudyBoardDetail/StudyBoardDetail.tsx, frontend/src/pages/StudyBoardDetail/components/Body.tsx, frontend/src/pages/StudyBoardDetail/components/Header.tsx, frontend/src/pages/StudyBoardDetail/style.ts
- 404페이지 라우터 연결
- 게시글 수정 접근 제한 기능 추가
- 글작성 및 글 수정 페이지 제목 및 태그 input CSS 수정
Resolved: #129 #131
=> FE: #129 #131 외

src/main/java/com/codestates/coco/comment/service/CommentService.java, src/main/java/com/codestates/coco/common/ErrorCode.java, src/main/java/com/codestates/coco/contents/controller/ContentController.java, src/main/java/com/codestates/coco/contents/domain/Content.java, src/main/java/com/codestates/coco/contents/domain/ContentDTO.java, src/main/java/com/codestates/coco/contents/service/ContentService.java, src/main/java/com/codestates/coco/user/config/CustomAuthenticationEntryPoint.java, src/main/java/com/codestates/coco/user/config/SecurityConfig.java, src/main/java/com/codestates/coco/user/controller/UserController.java, src/main/java/com/codestates/coco/user/domain/User.java, src/main/java/com/codestates/coco/user/jwt/JwtAuthenticationFilter.java, src/main/java/com/codestates/coco/user/jwt/JwtAuthorizationFilter.java, src/main/java/com/codestates/coco/user/jwt/JwtProvider.java, src/main/java/com/codestates/coco/user/repository/UserRepository.java, src/main/java/com/codestates/coco/user/service/UserService.java
@5witchkr
[feat: add commentCount logic]
@Minoolian
[Feat: "Profile의 username 수정 시 token 재발행"]
@Minoolian
[Feat: "게시글에 대한 사용자 Favor Status 추가"]
@Minoolian
[Fix: "접근권한 수정"]
@Minoolian
[Feat: "JWT 토큰관련 예외처리 추가 및 수정"]
=> BE: commentCount, token 재발행, Favor Status, 접근권한, JWT exception"

frontend/src/Router.tsx, frontend/src/apis/apiClient.ts
FE : "Scroll Top , Error Messege"
=> FE : "Scroll Top , Error Messege"

frontend/src/apis/types.ts, frontend/src/pages/BoardEdit/BoardEdit.tsx, frontend/src/pages/BoardWrite/BoardWrite.tsx
- 글 수정 페이지 태그 기능 추가
- 글 쓰기 페이지 태그 기능 엔터키 인식 오류 수정
=> FE: 글 수정 페이지 태그 기능 추가, 글 쓰기 페이지 태그 기능 오류 수정

frontend/.babelrc, frontend/.eslintrc, frontend/config/webpack.common.js, frontend/config/webpack.dev.js, frontend/config/webpack.prod.js, frontend/package-lock.json, frontend/package.json, frontend/src/Router.tsx, frontend/src/apis/apiClient.ts, frontend/src/apis/types.ts, frontend/src/pages/BoardEdit/BoardEdit.tsx, frontend/src/pages/BoardWrite/BoardWrite.tsx, frontend/src/pages/StudyBoard/StudyBoard.tsx, frontend/tsconfig.json
- Scroll Top 기능 추가
- api 에러메세지 수정
- 글 수정 페이지 태그 기능 추가
- 글쓰기 페이지 태그 기능 엔터키 인식 오류 수정
Resolved: #141
=> FE: #141 외

src/main/java/com/codestates/coco/contents/controller/ContentController.java, src/main/java/com/codestates/coco/contents/domain/Content.java, src/main/java/com/codestates/coco/contents/domain/ContentDTO.java, src/main/java/com/codestates/coco/contents/repository/ContentRepository.java, src/main/java/com/codestates/coco/contents/service/ContentService.java
* ContentController [Get]api/content/tag?tag={String}&page={int}
* add ContentDto&Content - List<String> tag
* add ContentRepository - findByTag-Method
=> Feat: tag Logic

src/main/java/com/codestates/coco/contents/controller/ContentController.java, src/main/java/com/codestates/coco/contents/domain/Content.java, src/main/java/com/codestates/coco/contents/domain/ContentDTO.java, src/main/java/com/codestates/coco/contents/service/ContentService.java
content 조회수 기능
* add contentController [get]/{id} - httpservletReq.getRemoteAddr
* add contentDTO Long viewCount
* add contentDTO content builder new userIpList
* add content domain Long viewCount, List<String> userIpList
* add content domain method addViewCount, addUserIplist
* add contentService create content- addvicwCount, addUserIpList
* add contentService get one content- viewcount++, viewcount UserIp valdate
* todo userIp encrypt
=> Feat: Content view

frontend/src/lib/types/index.ts, frontend/src/pages/StudyBoardDetail/components/Body.tsx, frontend/src/pages/StudyBoardDetail/style.ts
- 태그 UI 추가
- 태그 UI 추가에 따른 CSS 추가
- 태그 UI 추가에 따른 타입 추가
=> FE: 글 상세 페이지 태그 UI 추가

frontend/src/apis/apiClient.ts, frontend/src/apis/types.ts, frontend/src/pages/BoardEdit/BoardEdit.tsx, frontend/src/pages/BoardWrite/BoardWrite.tsx, frontend/src/pages/StudyBoardDetail/components/Body.tsx
- 글쓰기 페이지 및 글 수정 페이지 api post 데이터 수정
- tag 검색 기능 api 적용
=> FE: 글쓰기 페이지 및 글 수정 페이지 api post 데이터 수정, tag 검색 api 적용

frontend/src/Router.tsx, frontend/src/apis/apiClient.ts, frontend/src/components/ContentLayout/Left/LeftMenubar.tsx, frontend/src/hooks/useInfiQry.tsx, frontend/src/lib/types/index.ts, frontend/src/pages/MyCommentPage/MyCommentPage.tsx, frontend/src/pages/MyCommentPage/index.tsx, frontend/src/pages/MyCommentPage/style.ts, frontend/src/pages/MyFavorPage/MyFavorPage.tsx, frontend/src/pages/StudyBoard/StudyBoard.tsx
=> FE: 자신이 코멘트한 페이지 조회, 바뀐 데이터 적용
